"""Unit and integration tests for BounScraperClient and flow pipeline."""

from urllib.parse import parse_qs

import httpx
import pytest

from boun_scrape.domain.models import Department
from boun_scrape.scraper.client import (
    BounHttpError,
    BounScraperClient,
    RecaptchaBlockedError,
    decode_windows_1254,
    load_recaptcha_token,
    parse_cookie_file,
    parse_cookie_text,
    parse_curl_command,
)
from boun_scrape.scraper.flow import (
    discover_terms,
    fetch_department_schedule,
    fetch_departments,
    scrape_term_pipeline,
)

SAMPLE_SEMESTER_HTML = """
<!DOCTYPE html>
<html>
<body>
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="vs_token_123" />
<input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="gen_token_456" />
<input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="val_token_789" />

<select name="ctl00$cphMainContent$ddlSemester" id="ctl00_cphMainContent_ddlSemester">
    <option value="2024/2025-2">2024/2025-2</option>
    <option value="2024/2025-1" selected="selected">2024/2025-1</option>
    <option value="2023/2024-3">2023/2024-3</option>
</select>

<table class="table-bordered">
    <tr><td><a href="/scripts/sch.asp?donem=2024/2025-1&kisaadi=CMPE&bolum=COMPUTER+ENGINEERING">COMPUTER ENGINEERING</a></td></tr>
    <tr><td><a href="/scripts/sch.asp?donem=2024/2025-1&kisaadi=MATH&bolum=MATHEMATICS">MATHEMATICS</a></td></tr>
</table>
</body>
</html>
"""

SAMPLE_SCHEDULE_HTML = """
<!DOCTYPE html>
<html>
<body>
<table>
    <tr class="schtd">
        <td>CMPE 150.01</td>
        <td>Description</td>
        <td>INTRO TO COMPUTING</td>
        <td>3</td>
        <td>6</td>
        <td>PROF ALICE</td>
        <td>M Th</td>
        <td>12 3</td>
        <td>Face-to-Face</td>
        <td>NH101</td>
        <td>NH101 | BM101</td>
        <td>2025-01-10</td>
        <td></td>
        <td>CMPE</td>
        <td>EE, IE</td>
    </tr>
</table>
</body>
</html>
"""


class TestCookieParsing:
    """Tests for Netscape and header cookie string parsing."""

    def test_parse_netscape_format(self) -> None:
        raw_netscape = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

.bogazici.edu.tr	TRUE	/	FALSE	1750000000	ASP.NET_SessionId	abcd1234efgh
#HttpOnly_.bogazici.edu.tr	TRUE	/	TRUE	1750000000	buis_auth	auth_token_xyz
"""
        cookies = parse_cookie_text(raw_netscape)
        assert cookies["ASP.NET_SessionId"] == "abcd1234efgh"
        assert cookies["buis_auth"] == "auth_token_xyz"

    def test_parse_key_value_string(self) -> None:
        raw = "session_id=12345; user_pref=dark_mode"
        cookies = parse_cookie_text(raw)
        assert cookies["session_id"] == "12345"
        assert cookies["user_pref"] == "dark_mode"

    def test_parse_cookie_file(self, tmp_path) -> None:
        file = tmp_path / "cookies.txt"
        file.write_text("token=secret123", encoding="utf-8")
        cookies = parse_cookie_file(file)
        assert cookies["token"] == "secret123"

        assert parse_cookie_file(tmp_path / "nonexistent.txt") == {}


class TestRecaptchaTokenLoading:
    """Tests for loading a manually-solved reCAPTCHA token from a file."""

    def test_load_recaptcha_token_from_file(self, tmp_path) -> None:
        file = tmp_path / "recaptcha_token.txt"
        file.write_text("  a-fresh-token-value  \n", encoding="utf-8")
        assert load_recaptcha_token(str(file)) == "a-fresh-token-value"

    def test_load_recaptcha_token_missing_file(self, tmp_path) -> None:
        assert load_recaptcha_token(str(tmp_path / "nonexistent.txt")) == ""


class TestParseCurlCommand:
    """Tests for extracting cookies/reCAPTCHA token from a pasted curl command."""

    def test_extracts_cookie_flag_and_recaptcha_field(self) -> None:
        curl_text = (
            "curl 'https://registration.bogazici.edu.tr/BUIS/General/schedule.aspx?p=semester' \\\n"
            "  -H 'Accept: text/html' \\\n"
            "  -b 'ASP.NET_SessionId=abc123; ASPSESSIONIDXYZ=def456' \\\n"
            "  -H 'Origin: https://registration.bogazici.edu.tr' \\\n"
            "  --data-raw '__VIEWSTATE=someVsValue&ctl00%24cphMainContent%24ddlSemester=2024%2F2025-1"
            "&ctl00%24cphMainContent%24gRecResp=solved-token-value'"
        )
        result = parse_curl_command(curl_text)
        assert result["cookies"] == "ASP.NET_SessionId=abc123; ASPSESSIONIDXYZ=def456"
        assert result["recaptcha_token"] == "solved-token-value"

    def test_extracts_cookie_from_header_flag(self) -> None:
        curl_text = "curl 'https://example.com' -H 'Cookie: session=xyz789'"
        result = parse_curl_command(curl_text)
        assert result["cookies"] == "session=xyz789"

    def test_missing_recaptcha_field_returns_empty(self) -> None:
        curl_text = (
            "curl 'https://example.com' -b 'session=abc' "
            "--data-raw 'ctl00%24cphMainContent%24gRecResp='"
        )
        result = parse_curl_command(curl_text)
        assert result["cookies"] == "session=abc"
        assert result["recaptcha_token"] == ""

    def test_no_cookie_or_data_returns_empty_dict_values(self) -> None:
        result = parse_curl_command("curl 'https://example.com'")
        assert result == {"cookies": "", "recaptcha_token": ""}


class TestScraperClient:
    """Tests for BounScraperClient behaviors, retries, and errors."""

    @pytest.mark.asyncio
    async def test_client_windows_1254_decoding(self) -> None:
        turkish_text = "Boğaziçi Üniversitesi Bilgisayar Mühendisliği"
        encoded_content = turkish_text.encode("windows-1254")

        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(200, content=encoded_content)

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            resp = await client.get("/test")
            assert resp.text == turkish_text

    @pytest.mark.asyncio
    async def test_client_recaptcha_detection(self) -> None:
        recaptcha_page = """
        <html>
        <body>
        <h1>Warning</h1>
        <p>You could not pass the reCAPTCHA check. Access Denied.</p>
        </body>
        </html>
        """.encode("windows-1254")

        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(200, content=recaptcha_page)

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            with pytest.raises(RecaptchaBlockedError):
                await client.get("/test")

    @pytest.mark.asyncio
    async def test_client_retries_on_500_server_error(self) -> None:
        attempts = 0

        def handler(request: httpx.Request) -> httpx.Response:
            nonlocal attempts
            attempts += 1
            if attempts < 3:
                return httpx.Response(500, text="Internal Server Error")
            return httpx.Response(200, content=b"Success")

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            resp = await client.get("/test", retries=3)
            assert resp.status_code == 200
            assert attempts == 3

    @pytest.mark.asyncio
    async def test_recaptcha_token_property_rereads_file_fresh(self, tmp_path) -> None:
        file = tmp_path / "recaptcha_token.txt"
        file.write_text("first-token", encoding="utf-8")

        async_client = httpx.AsyncClient(
            transport=httpx.MockTransport(lambda r: httpx.Response(200)),
            base_url="https://registration.bogazici.edu.tr",
        )
        async with BounScraperClient(
            http_client=async_client,
            recaptcha_token_path=str(file),
            min_jitter=0,
            max_jitter=0,
        ) as client:
            assert client.recaptcha_token == "first-token"
            file.write_text("second-token", encoding="utf-8")
            assert client.recaptcha_token == "second-token"

    @pytest.mark.asyncio
    async def test_client_fails_when_retries_exhausted(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(502, text="Bad Gateway")

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            with pytest.raises(BounHttpError):
                await client.get("/test", retries=2)

    @pytest.mark.asyncio
    async def test_client_retries_on_429_too_many_requests_get(self) -> None:
        attempts = 0

        def handler(request: httpx.Request) -> httpx.Response:
            nonlocal attempts
            attempts += 1
            if attempts < 3:
                return httpx.Response(429, text="Too Many Requests")
            return httpx.Response(200, content=b"Success")

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            resp = await client.get("/test", retries=3)
            assert resp.status_code == 200
            assert attempts == 3

    @pytest.mark.asyncio
    async def test_client_retries_on_429_too_many_requests_post(self) -> None:
        attempts = 0

        def handler(request: httpx.Request) -> httpx.Response:
            nonlocal attempts
            attempts += 1
            if attempts < 3:
                return httpx.Response(429, text="Too Many Requests")
            return httpx.Response(200, content=b"Success")

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            resp = await client.post("/test", data={"key": "val"}, retries=3)
            assert resp.status_code == 200
            assert attempts == 3

    @pytest.mark.asyncio
    async def test_client_fails_immediately_on_404_without_retrying(self) -> None:
        attempts = 0

        def handler(request: httpx.Request) -> httpx.Response:
            nonlocal attempts
            attempts += 1
            return httpx.Response(404, text="Not Found")

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            with pytest.raises(BounHttpError) as exc_info:
                await client.get("/test", retries=3)
            assert exc_info.value.status_code == 404
            assert attempts == 1

    @pytest.mark.asyncio
    async def test_reload_cookies_updates_jar(self, tmp_path) -> None:
        cookie_file = tmp_path / "cookies.txt"
        cookie_file.write_text("session_id=init123", encoding="utf-8")

        async_client = httpx.AsyncClient(
            transport=httpx.MockTransport(lambda r: httpx.Response(200)),
            base_url="https://registration.bogazici.edu.tr",
        )
        async with BounScraperClient(
            http_client=async_client,
            cookies_path=str(cookie_file),
            min_jitter=0,
            max_jitter=0,
        ) as client:
            assert client.cookies.get("session_id") == "init123"
            cookie_file.write_text("session_id=fresh456; new_key=value789", encoding="utf-8")
            reloaded = client.reload_cookies()
            assert reloaded == {"session_id": "fresh456", "new_key": "value789"}
            assert client.cookies.get("session_id") == "fresh456"
            assert client.cookies.get("new_key") == "value789"


class TestScraperFlow:
    """Tests for scraping workflows and term pipeline."""

    @pytest.mark.asyncio
    async def test_discover_terms(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(
                200, content=SAMPLE_SEMESTER_HTML.encode("windows-1254")
            )

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            terms = await discover_terms(client)
            assert terms == ["2024/2025-2", "2024/2025-1", "2023/2024-3"]

    @pytest.mark.asyncio
    async def test_fetch_departments(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(
                200, content=SAMPLE_SEMESTER_HTML.encode("windows-1254")
            )

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            departments = await fetch_departments(client, "2024/2025-1")
            assert len(departments) == 2
            assert departments[0].code == "CMPE"
            assert departments[1].code == "MATH"

    @pytest.mark.asyncio
    async def test_fetch_departments_empty_post_does_not_substitute_wrong_term(self) -> None:
        EMPTY_DEPT_HTML = """
        <!DOCTYPE html>
        <html><body>
        <input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="vs_token_123" />
        <input type="hidden" name="__VIEWSTATEGENERATOR" id="__VIEWSTATEGENERATOR" value="gen_token_456" />
        <input type="hidden" name="__EVENTVALIDATION" id="__EVENTVALIDATION" value="val_token_789" />
        </body></html>
        """

        def handler(request: httpx.Request) -> httpx.Response:
            if request.method == "POST":
                # POST for the requested term returns no department table.
                return httpx.Response(200, content=EMPTY_DEPT_HTML.encode("windows-1254"))
            # Initial GET reflects a different (portal-default) term with departments.
            return httpx.Response(200, content=SAMPLE_SEMESTER_HTML.encode("windows-1254"))

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            departments = await fetch_departments(client, "2023/2024-3")
            assert departments == []

    @pytest.mark.asyncio
    async def test_fetch_departments_includes_recaptcha_token_in_post_body(self, tmp_path) -> None:
        token_file = tmp_path / "recaptcha_token.txt"
        token_file.write_text("solved-token-value", encoding="utf-8")
        captured_bodies: list[bytes] = []

        def handler(request: httpx.Request) -> httpx.Response:
            if request.method == "POST":
                captured_bodies.append(request.content)
            return httpx.Response(
                200, content=SAMPLE_SEMESTER_HTML.encode("windows-1254")
            )

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client,
            recaptcha_token_path=str(token_file),
            min_jitter=0,
            max_jitter=0,
        ) as client:
            await fetch_departments(client, "2024/2025-1")

        assert len(captured_bodies) == 1
        posted = parse_qs(captured_bodies[0].decode("utf-8"))
        assert posted["ctl00$cphMainContent$gRecResp"] == ["solved-token-value"]

    @pytest.mark.asyncio
    async def test_fetch_department_schedule(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(
                200, content=SAMPLE_SCHEDULE_HTML.encode("windows-1254")
            )

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            courses = await fetch_department_schedule(
                client, "2024/2025-1", Department(code="CMPE", name="COMPUTER ENGINEERING")
            )
            assert len(courses) == 1
            assert courses[0].course_code == "CMPE 150"
            assert courses[0].section == "01"
            assert len(courses[0].slots) == 2

    @pytest.mark.asyncio
    async def test_scrape_term_pipeline(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            if "schedule.aspx" in request.url.path:
                return httpx.Response(
                    200, content=SAMPLE_SEMESTER_HTML.encode("windows-1254")
                )
            if "sch.asp" in request.url.path:
                return httpx.Response(
                    200, content=SAMPLE_SCHEDULE_HTML.encode("windows-1254")
                )
            return httpx.Response(404)

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        progress_calls: list[tuple[int, int, str]] = []

        def on_progress(completed: int, total: int, dept: Department, courses) -> None:
            progress_calls.append((completed, total, dept.code))

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            result = await scrape_term_pipeline(
                client,
                "2024/2025-1",
                progress_callback=on_progress,
                concurrency=2,
            )
            assert len(result.courses) == 2  # 1 course each for 2 depts
            assert sorted(result.succeeded_departments) == ["CMPE", "MATH"]
            assert result.failed_departments == []
            assert len(progress_calls) == 2
            assert progress_calls[-1][0] == 2
            assert progress_calls[-1][1] == 2

    @pytest.mark.asyncio
    async def test_scrape_term_pipeline_reports_partial_department_failure(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            if "schedule.aspx" in request.url.path:
                return httpx.Response(
                    200, content=SAMPLE_SEMESTER_HTML.encode("windows-1254")
                )
            if "sch.asp" in request.url.path:
                if "kisaadi=CMPE" in str(request.url):
                    return httpx.Response(500, text="Internal Server Error")
                return httpx.Response(
                    200, content=SAMPLE_SCHEDULE_HTML.encode("windows-1254")
                )
            return httpx.Response(404)

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            result = await scrape_term_pipeline(
                client, "2024/2025-1", concurrency=2,
            )
            assert result.succeeded_departments == ["MATH"]
            assert result.failed_departments == ["CMPE"]
            assert len(result.courses) == 1

    @pytest.mark.asyncio
    async def test_scrape_term_pipeline_drops_into_heuristic_mode_when_captcha_blocked(
        self,
    ) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            if "schedule.aspx" in request.url.path:
                # Simulates reCAPTCHA block on discovery page
                return httpx.Response(
                    200,
                    text="<html><body>You could not pass the reCAPTCHA check</body></html>",
                )
            if "sch.asp" in request.url.path:
                # sch.asp succeeds with courses
                return httpx.Response(
                    200, content=SAMPLE_SCHEDULE_HTML.encode("windows-1254")
                )
            return httpx.Response(404)

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            # Target a historical term with no cached departments; should drop into heuristic mode
            result = await scrape_term_pipeline(
                client, "1971/1972-2", target_departments=["CMPE", "MATH"], concurrency=2
            )
            assert "CMPE" in result.succeeded_departments
            assert "MATH" in result.succeeded_departments
            assert len(result.courses) == 2

    @pytest.mark.asyncio
    async def test_retry_after_header_numeric_seconds(self) -> None:
        attempts = 0
        delays: list[float] = []

        def handler(request: httpx.Request) -> httpx.Response:
            nonlocal attempts
            attempts += 1
            if attempts == 1:
                return httpx.Response(
                    429,
                    headers={"Retry-After": "0.01"},
                    text="Rate Limited",
                )
            return httpx.Response(200, content=b"Success")

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            resp = await client.get("/test", retries=2)
            assert resp.status_code == 200
            assert attempts == 2

    @pytest.mark.asyncio
    async def test_retry_after_header_http_date_and_503(self) -> None:
        from datetime import datetime, timezone, timedelta
        import email.utils

        attempts = 0
        future_dt = datetime.now(timezone.utc) + timedelta(seconds=1)
        http_date = email.utils.format_datetime(future_dt)

        def handler(request: httpx.Request) -> httpx.Response:
            nonlocal attempts
            attempts += 1
            if attempts == 1:
                return httpx.Response(
                    503,
                    headers={"Retry-After": http_date},
                    text="Service Unavailable",
                )
            return httpx.Response(200, content=b"Success")

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            resp = await client.post("/test", data={"k": "v"}, retries=2)
            assert resp.status_code == 200
            assert attempts == 2

    @pytest.mark.asyncio
    async def test_recaptcha_token_invalidated_after_use_in_fetch_departments(
        self, tmp_path
    ) -> None:
        token_file = tmp_path / "recaptcha_token.txt"
        token_file.write_text("single-use-token", encoding="utf-8")

        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(
                200, content=SAMPLE_SEMESTER_HTML.encode("windows-1254")
            )

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client,
            recaptcha_token_path=str(token_file),
            min_jitter=0,
            max_jitter=0,
        ) as client:
            assert client.recaptcha_token == "single-use-token"
            await fetch_departments(client, "2024/2025-1")
            assert token_file.read_text(encoding="utf-8") == ""
            assert client.recaptcha_token == ""

    @pytest.mark.asyncio
    async def test_recaptcha_token_invalidated_on_captcha_blocked_response(
        self, tmp_path
    ) -> None:
        token_file = tmp_path / "recaptcha_token.txt"
        token_file.write_text("invalid-token", encoding="utf-8")

        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(
                200,
                content="<html><body>You could not pass the reCAPTCHA check</body></html>".encode(
                    "windows-1254"
                ),
            )

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client,
            recaptcha_token_path=str(token_file),
            min_jitter=0,
            max_jitter=0,
        ) as client:
            with pytest.raises(RecaptchaBlockedError):
                await client.get("/test")
            assert token_file.read_text(encoding="utf-8") == ""
            assert client.recaptcha_token == ""

    @pytest.mark.asyncio
    async def test_scrape_term_pipeline_fallback_to_cached_departments(self) -> None:
        cached = [
            Department(code="CMPE", name="Computer Engineering", bolum="COMPUTER ENGINEERING"),
            Department(code="MATH", name="Mathematics", bolum="MATHEMATICS"),
        ]

        def handler(request: httpx.Request) -> httpx.Response:
            url_str = str(request.url)
            if "schedule.aspx" in url_str:
                # Simulate expired cookies / CAPTCHA failure on semester page
                return httpx.Response(
                    200,
                    content="<html><body>You could not pass the reCAPTCHA check</body></html>".encode(
                        "windows-1254"
                    ),
                )
            if "sch.asp" in url_str:
                # Schedule pages succeed without cookies or captcha
                return httpx.Response(
                    200, content=SAMPLE_SCHEDULE_HTML.encode("windows-1254")
                )
            return httpx.Response(404)

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            result = await scrape_term_pipeline(
                client,
                term="2024/2025-1",
                cached_departments=cached,
            )
            assert len(result.succeeded_departments) == 2
            assert "CMPE" in result.succeeded_departments
            assert "MATH" in result.succeeded_departments
            assert len(result.courses) > 0

    @pytest.mark.asyncio
    async def test_scrape_term_pipeline_heuristic_mode_without_cache(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            url_str = str(request.url)
            if "schedule.aspx" in url_str:
                # Discovery blocked by reCAPTCHA
                return httpx.Response(
                    200,
                    content="<html><body>You could not pass the reCAPTCHA check</body></html>".encode(
                        "windows-1254"
                    ),
                )
            if "sch.asp" in url_str:
                # Direct schedule pages work
                return httpx.Response(
                    200, content=SAMPLE_SCHEDULE_HTML.encode("windows-1254")
                )
            return httpx.Response(404)

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            result = await scrape_term_pipeline(
                client,
                term="1971/1972-2",
                cached_departments=None,
                target_departments=["CMPE"],
            )
            assert "CMPE" in result.succeeded_departments
            assert len(result.courses) == 1

    @pytest.mark.asyncio
    async def test_scrape_term_pipeline_fallback_raises_when_all_fail(self) -> None:
        def handler(request: httpx.Request) -> httpx.Response:
            return httpx.Response(500, text="Internal Server Error")

        transport = httpx.MockTransport(handler)
        async_client = httpx.AsyncClient(
            transport=transport, base_url="https://registration.bogazici.edu.tr"
        )

        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            with pytest.raises(Exception):
                await scrape_term_pipeline(
                    client,
                    term="2024/2025-1",
                    cached_departments=None,
                    target_departments=["CMPE"],
                )

    @pytest.mark.asyncio
    async def test_client_rejects_ssrf_disallowed_origin(self) -> None:
        async_client = httpx.AsyncClient(
            transport=httpx.MockTransport(lambda r: httpx.Response(200)),
            base_url="https://registration.bogazici.edu.tr",
        )
        async with BounScraperClient(
            http_client=async_client, min_jitter=0, max_jitter=0
        ) as client:
            with pytest.raises(BounHttpError, match="Disallowed target URL origin"):
                await client.get("http://169.254.169.254/latest/meta-data")
            with pytest.raises(BounHttpError, match="Disallowed target URL origin"):
                await client.post("https://evil.attacker.com/steal", data={"leak": "1"})

